# AppLevel Configurations
streamer:
  video_path : "assets/data/gt/top-100-shots-rallies-2018-atp-season.mp4" # Path of the video
  img_path : "/home/hardy/Workspace/Python/SportRadar/AnnotationCreator/assets/dataset/split/test/images" # Dir of test images
  should_draw : true # Draws the result if enabled
  debug : false # turn on or off debug logs
  evaluation : true # Calculates the average matching names, scores, serving player over the test dataset.

# Model Paths
models:
  score_det_model: "assets/models/best.onnx" # Model path of the Detector
  detector_config : "assets/configs/detector_config.yaml"
  text_rec_model : "/home/hardy/Workspace/Python/SportRadar/ScoreWatch/assets/models/text_recog.pth" # Model path of CRNN
  text_rec_config : "assets/configs/text_rec_config.yaml"
  ocr_engine : "CRNN" # CRNN or PyTesseract

logs:
  json_path : ""